AWS_UPLOAD_BUCKET = "upload-users-post"

AWS_UPLOAD_USERNAME = "Kishan"

AWS_UPLOAD_GROUP = "CFE_AwesomeGroup"

AWS_UPLOAD_REGION = 'ap-south-1'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIATJCOVRZIUPERV3M3"

AWS_UPLOAD_SECRET_KEY = "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"